### ISSUE TITLE
IdeaAudio - does it have java wrapper?

### ISSUE THREAD

**Issue by jkody** [robelsharma/IdeaAudio#2] opened 2016-05-23 15:57 UTC
Hi :)

I watched the stackoverflow issue http://stackoverflow.com/a/17993976/6312069 which describes how to get io devices list; But I couldn't get it... does the IdeaAudio have java wrapper?

Thanks

**Comment by robelsharma** [comment] 2016-05-24 18:12
Duplicate of #1

**Closed as completed** 2016-05-24 18:11 UTC
